### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by Mortezanavidi** [skapadia3214/groq-moa#7]
here is the error:
`
Traceback (most recent call last):
  File "streamlit\runtime\scriptrunner\exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
  File "streamlit\runtime\scriptrunner\script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "groq-moa\app.py", line 5, in <module>
    from moa.agent import MOAgent
  File "groq-moa\moa\agent\__init__.py", line 1, in <module>
    from .moa import MOAgent
  File "groq-moa\moa\agent\moa.py", line 33, in <module>
    class MOAgent:
  File "groq-moa\moa\agent\moa.py", line 143, in MOAgent
    ) -> Generator[str | ResponseChunk, None, None]:
TypeError: unsupported operand type(s) for |: 'type' and '_TypedDictMeta'
`

the older version works but after recent update i get this error

**Comment by skapadia3214** [comment]
Which version of Python are you using?

**Comment by Mortezanavidi** [comment]
3.9

**Comment by skapadia3214** [comment]
You need to use Python 3.10+ to run this repo. The | type union operator is not supported in Python 3.9. See [this](https://docs.python.org/3/whatsnew/3.10.html#pep-604-new-type-union-operator) for more details.
